### ISSUE TITLE
panic: unexpected object with 1 implicit type parameter(s)

### ISSUE THREAD

**Issue by cinemast** [kyoh86/looppointer#18]
```panic: unexpected object with 1 implicit type parameter(s)

goroutine 2143 [running]:
golang.org/x/tools/go/internal/gcimporter.errorf(...)
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/internal/gcimporter/bimport.go:171
golang.org/x/tools/go/internal/gcimporter.(*pkgReader).objDictIdx(0xc004b306c0, 0x4e13cb0?)
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/internal/gcimporter/ureader_yes.go:591 +0x399
golang.org/x/tools/go/internal/gcimporter.(*pkgReader).objIdx(0xc004b306c0, 0x6?)
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/internal/gcimporter/ureader_yes.go:494 +0x225
golang.org/x/tools/go/internal/gcimporter.readUnifiedPackage(0xc0000297c0, 0x0, 0xc00534aae0, {0x1, 0x0, {0xc0001941b0, 0x23}, {0xc0027069e0, 0x20e9e}, {0xc001ea4000, ...}, ...})
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/internal/gcimporter/ureader_yes.go:110 +0x45b
golang.org/x/tools/go/internal/gcimporter.UImportData(0xee8460?, 0xc0007e6480?, {0xc002618001?, 0x45?, 0xc00534aae0?}, {0xc0001941b0, 0x23})
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/internal/gcimporter/ureader_yes.go:68 +0x12a
golang.org/x/tools/go/gcexportdata.Read({0xee8460?, 0xc0007e6480?}, 0x0?, 0x0?, {0xc0001941b0, 0x23})
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/gcexportdata/gcexportdata.go:134 +0x2b0
golang.org/x/tools/go/packages.(*loader).loadFromExportData(0xc00014a000, 0xc000e26ba0)
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/packages/packages.go:1278 +0x472
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc00014a000, 0xc000e26ba0)
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/packages/packages.go:882 +0x56a
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/packages/packages.go:847 +0x1a9
sync.(*Once).doSlow(0x0?, 0x0?)
        C:/Program Files/Go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        C:/Program Files/Go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/packages/packages.go:835 +0x52
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/packages/packages.go:842 +0x2c
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1
        C:/Users/cinemast/go/pkg/mod/golang.org/x/tools@v0.2.0/go/packages/packages.go:841 +0x8f```

**Comment by kyoh86** [comment]
@cinemast Could you give me a code to reproduce it?
I can't reproduce it in my hand.

**Comment by kyoh86** [comment]
This is not planned because Go doesn't need `looppointer` more.
